name: Node.js Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    env:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: coffeebreak
    
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
    
      - name: Fetch
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
       
      - name: Test
        run: |
          npm ci
          node index.js &
          npm test
